services:
  server:
    container_name: MokaServer
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
    dns:
      - 8.8.8.8
      - 8.8.4.4