### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "testA",
  "email": "testa@gmail.com",
  "password": "MotDePasseTresSecret123"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "MotDePasseTresSecret123"
}

###

POST http://localhost:3000/fridge/1/ingredients
Content-Type: application/json

{
  "ingredients": [
    { "name": "fromage", "quantity": 1, "unite": "pièce" },
    { "name": "bavette", "quantity": 2, "unite": "grammes" },
    { "name": "oeufs", "quantity": 6, "unite": "unité" }
  ]
}

###
GET http://localhost:3000/fridge/1/ingredients
Content-Type: application/json


###
GET http://localhost:3000/fridge/1/ingredients/category?category=viande
Content-Type: application/json


###
DELETE http://localhost:3000/fridge/ingredient/4
Content-Type: application/json

###
POST http://localhost:3000/list/
Content-Type: application/json

{
  "userId": "6e3a3d07-bade-4357-8f3d-4de50fc58f25",
  "listName": "Courses Rapido",
  "ingredientsIds": [9, 7, 15]
}

###
POST http://localhost:3000/list/1/complete
Content-Type: application/json

{
  "userId": "6e3a3d07-bade-4357-8f3d-4de50fc58f25",
  "listId": 4
}

###
GET http://localhost:3000/list/6e3a3d07-bade-4357-8f3d-4de50fc58f25
Content-Type: application/json

###
GET http://localhost:3000/list/detail/4
Content-Type: application/json

###
DELETE http://localhost:3000/list/4?userId=6e3a3d07-bade-4357-8f3d-4de50fc58f25

###
PUT http://localhost:3000/list/1
Content-Type: application/json

{
  "userId": "35a56c00-9a9c-4cb9-bbf8-c63f63bc7e74",
  "listName": "Courses de la semaine bis",
  "ingredientsIds": [21, 25, 30]
}